services:
#    location_voiture.example:
#        class: locationVoitureBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    locationVoitureBundle.Statistiques:
      class: locationVoitureBundle\Statistiques\StatistiquesService
